train: [ 
D:\VISEM_Tracking_Train_v4\Train\13
D:\VISEM_Tracking_Train_v4\Train\14
D:\VISEM_Tracking_Train_v4\Train\15
D:\VISEM_Tracking_Train_v4\Train\19
D:\VISEM_Tracking_Train_v4\Train\21
D:\VISEM_Tracking_Train_v4\Train\22
D:\VISEM_Tracking_Train_v4\Train\23
D:\VISEM_Tracking_Train_v4\Train\24
D:\VISEM_Tracking_Train_v4\Train\29
D:\VISEM_Tracking_Train_v4\Train\30
D:\VISEM_Tracking_Train_v4\Train\35
D:\VISEM_Tracking_Train_v4\Train\36
D:\VISEM_Tracking_Train_v4\Train\38
D:\VISEM_Tracking_Train_v4\Train\52
D:\VISEM_Tracking_Train_v4\Train\60
D:\VISEM_Tracking_Train_v4\Train\82
]

val: [
D:\VISEM_Tracking_Train_v4\Val\11
D:\VISEM_Tracking_Train_v4\Val\12
D:\VISEM_Tracking_Train_v4\Val\47
D:\VISEM_Tracking_Train_v4\Val\54
]

nc: 3

names: [ "sperm", "cluster", "small_or_pinhead"]